---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: data_bags
    driver:
      network:
        - ["private_network", {ip: "192.168.17.19"}]
    run_list:
      - recipe[marcelo_app_ruby_2::default]